# Generated by Django 4.1.7 on 2023-06-15 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['date', 'student', 'status'], 'verbose_name_plural': 'Attendance'},
        ),
    ]
