# Generated by Django 4.2.2 on 2023-07-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='today_date',
            field=models.DateField(unique=True),
        ),
    ]
