# Generated by Django 4.1.7 on 2023-07-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_alter_date_today_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='today_date',
            field=models.DateField(),
        ),
    ]
