# Generated by Django 4.2.2 on 2023-07-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0003_alter_date_today_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='today_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
