# Generated by Django 4.2.2 on 2023-07-07 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'Person'},
        ),
        migrations.AlterModelTable(
            name='person',
            table='Person',
        ),
    ]
