# Generated by Django 4.2.2 on 2023-06-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0002_alter_person_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='my_image',
            field=models.ImageField(null=True, upload_to='profile_img/'),
        ),
    ]
