# Generated by Django 4.2.2 on 2023-06-23 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0003_person_my_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='course',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Attendance.course'),
        ),
    ]
