# Generated by Django 4.2.2 on 2023-06-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0004_person_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='my_image',
            field=models.ImageField(default='noimage', null=True, upload_to='profile_img/'),
        ),
    ]
