# Generated by Django 4.2.2 on 2023-06-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0005_alter_person_my_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='my_image',
            field=models.ImageField(null=True, upload_to='profile_img/'),
        ),
    ]
